name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get -y install docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
      - name: Checkout
        uses: actions/checkout@v3

  docker:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/min-project:latest

  deploy-rest-api:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker stop restapi  
            sudo docker rm restapi
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/min-project:latest
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/min-project:latest
            sudo docker run -d -p 8001:8001 -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -e DBUSER=${{ secrets.DB_USERNAME }} -e DBPASS=${{ secrets.DB_PASSWORD }} -e DBHOST=${{ secrets.DB_HOST }} -e DBPORT=${{ secrets.DB_PORT }} -e DBNAME=${{ secrets.DB_NAME }} -e SECRET_JWT=${{ secrets.SECRET_KEY }} --name restapi ${{ secrets.DOCKERHUB_USERNAME }}/min-project:latest
